version: "3.7"
services:
  database:
    image: postgres
    container_name: 'to-do-db'
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports: 
      - 5440:5432
    volumes:
      - pgdata:/data/postgres
    restart: always

  api:
    build: .
    container_name: 'to-do-api'
    restart: always
    working_dir: /usr/app/src
    ports:
      - 3335:3335
    volumes:
      - ./src:/usr/app/src
      - ./tmp:/usr/app/tmp
    links:
      - database
    depends_on:
      - database

volumes:
    pgdata:
        driver: local